export const enum BasedOn {
  FIXED_PRICE = 'FIXED_PRICE',

  PRODUCT_COUNT = 'PRODUCT_COUNT',

  SHOPIFY_PLAN = 'SHOPIFY_PLAN',

  PRODUCT_COUNT_AND_SHOPIFY_PLAN = 'PRODUCT_COUNT_AND_SHOPIFY_PLAN',

  SUBSCRIPTION_ORDER_AMOUNT = 'SUBSCRIPTION_ORDER_AMOUNT'
}
