export const enum BillingAttemptStatus {
  SUCCESS = 'SUCCESS',

  FAILURE = 'FAILURE',

  REQUESTING = 'REQUESTING',

  PROGRESS = 'PROGRESS',

  QUEUED = 'QUEUED',

  SKIPPED = 'SKIPPED',

  SOCIAL_CONNECTION_NULL = 'SOCIAL_CONNECTION_NULL',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',

  CONTRACT_ENDED = 'CONTRACT_ENDED',

  CONTRACT_PAUSED = 'CONTRACT_PAUSED',

  AUTO_CHARGE_DISABLED = 'AUTO_CHARGE_DISABLED',

  SHOPIFY_EXCEPTION = 'SHOPIFY_EXCEPTION',

  SKIPPED_DUNNING_MGMT = 'SKIPPED_DUNNING_MGMT',

  SKIPPED_INVENTORY_MGMT = 'SKIPPED_INVENTORY_MGMT',

  IMMEDIATE_TRIGGERED = 'IMMEDIATE_TRIGGERED',

  SECURITY_CHALLENGE = 'SECURITY_CHALLENGE',

  CONTRACT_PAUSED_MAX_CYCLES = 'CONTRACT_PAUSED_MAX_CYCLES'
}
