export const enum CancellationTypeStatus {
  CANCEL_IMMEDIATELY = 'CANCEL_IMMEDIATELY',
  CANCELLATION_INSTRUCTIONS = 'CANCELLATION_INSTRUCTIONS',
  CUSTOMER_RETENTION_FLOW = 'CUSTOMER_RETENTION_FLOW',
  CANCEL_AFTER_PAUSE = 'CANCEL_AFTER_PAUSE'
}
