export const enum cardExpireEmailSentStatus {
  FIRST_ATTEMPT = 'FIRST_ATTEMPT',

  SECOND_ATTEMPT = 'SECOND_ATTEMPT',

  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  EMAIL_SETTINGS_DISABLED = 'EMAIL_SETTINGS_DISABLED',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED'
}
