export const enum CardExpireSmsSentStatus {
  FIRST_ATTEMPT = 'FIRST_ATTEMPT',

  SECOND_ATTEMPT = 'SECOND_ATTEMPT',

  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  SMS_SETTINGS_DISABLED = 'SMS_SETTINGS_DISABLED',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',

  PHONE_NUMBER_EMPTY = 'PHONE_NUMBER_EMPTY'
}
