export const enum DisplayPriceFormat {
  FIRST_VARIANT_PRICE,
  LOWEST_PRICE,
  LOWEST_AVAILABLE_PRICE,
  FROM_LOWEST_PRICE,
  FROM_LOWEST_AVAILABLE_PRICE,
  LOWEST_PRICE_HIGHEST_PRICE,
  LOWEST_AVAILABLE_PRICE_HIGHEST_AVAILABLE_PRICE
}
