export const enum EmailSettingType {
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',

  TRANSACTION_FAILED = 'TRANSACTION_FAILED',

  UPCOMING_ORDER = 'UPCOMING_ORDER',

  EXPIRING_CREDIT_CARD = 'EXPIRING_CREDIT_CARD',

  SHIPPING_ADDRESS_UPDATED = 'SHIPPING_ADDRESS_UPDATED',

  ORDER_FREQUENCY_UPDATED = 'ORDER_FREQUENCY_UPDATED',

  NEXT_ORDER_DATE_UPDATED = 'NEXT_ORDER_DATE_UPDATED',

  SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED',

  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',

  SUBSCRIPTION_RESUMED = 'SUBSCRIPTION_RESUMED',

  SUBSCRIPTION_PRODUCT_ADDED = 'SUBSCRIPTION_PRODUCT_ADDED',

  SUBSCRIPTION_PRODUCT_REMOVED = 'SUBSCRIPTION_PRODUCT_REMOVED',

  SUBSCRIPTION_PRODUCT_REPLACED = 'SUBSCRIPTION_PRODUCT_REPLACED',

  SECURITY_CHALLENGE = 'SECURITY_CHALLENGE',

  SUBSCRIPTION_MANAGEMENT_LINK = 'SUBSCRIPTION_MANAGEMENT_LINK',

  ORDER_SKIPPED = 'ORDER_SKIPPED',

  OUT_OF_STOCK = 'OUT_OF_STOCK',

  TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS',
}
