export const enum OnBoardingStatus {
  WELCOME,
  THEME,
  FILTERS,
  ANALYTICS,
  INDEXING,
  QUICK_TOUR,
  TEST_APP,
  COMPLETE,
  COLLECTION_FILTER_INSTALLATION_FEEDBACK,
  REVERT_THEME_INSTRUCTION
}
