export enum OnboardingChecklistStep {
  SUBSCRIPTION_PLANS = 'SUBSCRIPTION_PLANS',
  APPSTLE_WIDGET = 'APPSTLE_WIDGET',
  SHIPPING_PROFILE = 'SHIPPING_PROFILE',
  EMAIL_TEMPLATES = 'EMAIL_TEMPLATES',
  DUNNING_CANCELLATION = 'DUNNING_CANCELLATION',
  BUILD_A_BOX = 'BUILD_A_BOX',
  SUPPORT = 'SUPPORT'
}

export default OnboardingChecklistStep;
