export const enum OrderWebhookType {
  ORDER_CREATE = 'ORDER_CREATE',

  ORDER_FULFILLED = 'ORDER_FULFILLED',

  ORDER_PARTIALLY_FULFILLED = 'ORDER_PARTIALLY_FULFILLED',

  ORDER_CANCELLED = 'ORDER_CANCELLED',

  REFUND_ISSUED = 'REFUND_ISSUED',

  FULFILLMENT_UPDATED = 'FULFILLMENT_UPDATED',

  ACCOUNT_CREATE = 'ACCOUNT_CREATE',

  ACCOUNT_ACTIVATE = 'ACCOUNT_ACTIVATE'
}
