export const enum RecommendationWidgetType {
  NEW_PRODUCTS = 'NEW_PRODUCTS',
  FEATURED_PRODUCTS = 'FEATURED_PRODUCTS',
  SIMILAR_PRODUCTS = 'SIMILAR_PRODUCTS',
  MOST_POPULAR_PRODUCTS = 'MOST_POPULAR_PRODUCTS',
  PRODUCTS_BY_ATTRIBUTES = 'PRODUCTS_BY_ATTRIBUTES',
  CUSTOMERS_WHO_BOUGHT_THIS_ALSO_BOUGHT = 'CUSTOMERS_WHO_BOUGHT_THIS_ALSO_BOUGHT'
}
