export const enum RetryAttempts {
  ONE_ATTEMPT = 'ONE_ATTEMPT',

  TWO_ATTEMPTS = 'TWO_ATTEMPTS',

  THREE_ATTEMPTS = 'THREE_ATTEMPTS',

  FOUR_ATTEMPTS = 'FOUR_ATTEMPTS',

  FIVE_ATTEMPTS = 'FIVE_ATTEMPTS',

  SIX_ATTEMPTS = 'SIX_ATTEMPTS',

  SEVEN_ATTEMPTS = 'SEVEN_ATTEMPTS',

  EIGHT_ATTEMPTS = 'EIGHT_ATTEMPTS',

  NINE_ATTEMPTS = 'NINE_ATTEMPTS',

  TEN_ATTEMPTS = 'TEN_ATTEMPTS',

  ELEVEN_ATTEMPTS = 'ELEVEN_ATTEMPTS',

  TWELVE_ATTEMPTS = 'TWELVE_ATTEMPTS',

  THIRTEEN_ATTEMPTS = 'THIRTEEN_ATTEMPTS',

  FOURTEEN_ATTEMPTS = 'FOURTEEN_ATTEMPTS',

  FIFTEEN_ATTEMPTS = 'FIFTEEN_ATTEMPTS'
}
