export const enum SmsSettingType {
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',

  TRANSACTION_FAILED = 'TRANSACTION_FAILED',

  UPCOMING_ORDER = 'UPCOMING_ORDER',

  EXPIRING_CREDIT_CARD = 'EXPIRING_CREDIT_CARD'
}
