export const enum SubscriptionCreatedSmsSentStatus {
  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  SMS_SETTINGS_DISABLED = 'SMS_SETTINGS_DISABLED',

  CUSTOMER_PAYMENT_EMPTY = 'CUSTOMER_PAYMENT_EMPTY',

  CONTRACT_PAUSED_STATUS = 'CONTRACT_PAUSED_STATUS',

  PHONE_NUMBER_EMPTY = 'PHONE_NUMBER_EMPTY'
}
