export const enum SubscriptionType {
  REGULAR_SUBSCRIPTION = 'REGULAR_SUBSCRIPTION',

  BUILD_A_BOX_CLASSIC = 'BUILD_A_BOX_CLASSIC',

  BUILD_A_BOX_SINGLE_PRODUCT = 'BUILD_A_BOX_SINGLE_PRODUCT',

  BUNDLING_CLASSIC = 'BUNDLING_CLASSIC',

  BUNDLING_MIX_AND_MATCH = 'BUNDLING_MIX_AND_MATCH'
}
