export const enum transactionFailedEmailSentStatus {
  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  EMAIL_SETTINGS_DISABLED = 'EMAIL_SETTINGS_DISABLED',

  CUSTOMER_PAYMENT_EMPTY = 'CUSTOMER_PAYMENT_EMPTY',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED'
}
