export const enum TransactionFailedSmsSentStatus {
  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  SMS_SETTINGS_DISABLED = 'SMS_SETTINGS_DISABLED',

  CUSTOMER_PAYMENT_EMPTY = 'CUSTOMER_PAYMENT_EMPTY',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',

  PHONE_NUMBER_EMPTY = 'PHONE_NUMBER_EMPTY'
}
