export const enum upcomingOrderEmailSentStatus {
  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  EMAIL_SETTINGS_DISABLED = 'EMAIL_SETTINGS_DISABLED',

  CUSTOMER_PAYMENT_EMPTY = 'CUSTOMER_PAYMENT_EMPTY',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',

  STOP_FROM_CONTRACT = 'STOP_FROM_CONTRACT',

  CONTRACT_PAUSED = 'CONTRACT_PAUSED'
}
