export const enum UpcomingOrderSmsSentStatus {
  SENT = 'SENT',

  UNSENT = 'UNSENT',

  FAILED = 'FAILED',

  SMS_SETTINGS_DISABLED = 'SMS_SETTINGS_DISABLED',

  CUSTOMER_PAYMENT_EMPTY = 'CUSTOMER_PAYMENT_EMPTY',

  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',

  STOP_FROM_CONTRACT = 'STOP_FROM_CONTRACT',

  CONTRACT_PAUSED = 'CONTRACT_PAUSED',

  PHONE_NUMBER_EMPTY = 'PHONE_NUMBER_EMPTY'
}
