import { CustomerPortalMode } from 'app/shared/model/enumerations/customer-portal-mode.model';
import { ScriptVersion } from 'app/shared/model/enumerations/script-version.model';
import { BuildBoxVersion } from 'app/shared/model/enumerations/build-box-version.model';
import { OrderDayOfWeek } from 'app/shared/model/enumerations/order-day-of-week.model';

export interface IShopInfo {
  id?: number;
  shop?: string;
  apiKey?: string;
  shopTimeZone?: string;
  shopifyPlanDisplayName?: string;
  shopifyPlanName?: string;
  searchResultPageId?: number;
  publicDomain?: string;
  moneyFormat?: string;
  currency?: string;
  onboardingSeen?: boolean;
  devEnabled?: boolean;
  firstTimeOrderTag?: string;
  recurringOrderTag?: string;
  customerActiveSubscriptionTag?: string;
  customerInActiveSubscriptionTag?: string;
  customerPausedSubscriptionTag?: string;
  emailCustomDomain?: string;
  loyaltyLionToken?: string;
  loyaltyLionSecret?: string;
  loyaltyLionPoints?: number;
  loyaltyLionMultiplier?: number;
  loyaltyLionEnabled?: boolean;
  growaveClientId?: string;
  growaveSecret?: string;
  growavePoints?: number;
  growaveMultiplier?: number;
  growaveEnabled?: boolean;
  yotpoApiKey?: string;
  yotpoGuid?: string;
  yotpoPoints?: number;
  yotpoMultiplier?: number;
  yotpoEnabled?: boolean;
  klaviyoPublicApiKey?: string;
  klaviyoApiKey?: string;
  omniSendApiKey?: string;
  manageSubscriptionsUrl?: string;
  zapierSubscriptionCreatedUrl?: string;
  zapierSubscriptionUpdatedUrl?: string;
  zapierRecurringOrderPlacedUrl?: string;
  zapierCustomerSubscriptionsUpdatedUrl?: string;
  zapierNextOrderUpdatedUrl?: string;
  zapierOrderFrequencyUpdatedUrl?: string;
  zapierShippingAddressUpdatedUrl?: string;
  zapierSubscriptionCanceledUrl?: string;
  zapierSubscriptionPausedUrl?: string;
  zapierSubscriptionProductAddedUrl?: string;
  zapierSubscriptionProductRemovedUrl?: string;
  zapierSubscriptionActivatedUrl?: string;
  zapierSubscriptionTransactionFailedUrl?: string;
  zapierSubscriptionUpcomingOrderUrl?: string;
  zapierSubscriptionExpiringCreditCardUrl?: string;
  advancedCustomerPortal?: boolean;
  transferOrderNotesToSubscription?: boolean;
  transferOrderNoteAttributesToSubscription?: boolean;
  transferOrderLineItemAttributesToSubscription?: boolean;
  customerPortalMode?: CustomerPortalMode;
  recurringOrderTime?: string;
  recurringOrderHour?: number;
  recurringOrderMinute?: number;
  zoneOffsetHours?: number;
  zoneOffsetMinutes?: number;
  localOrderHour?: number;
  localOrderMinute?: number;
  stopImportProcess?: boolean;
  disableShippingPricingAutoCalculation?: boolean;
  allowV1FormCustomerPortal?: boolean;
  enableChangeFromNextBillingDate?: boolean;
  enableInventoryCheck?: boolean;
  whiteListed?: boolean;
  enableAddJSInterceptor?: boolean;
  reBuyEnabled?: boolean;
  priceSyncEnabled?: boolean;
  discountSyncEnabled?: boolean;
  skuSyncEnabled?: boolean;
  klaviyoListId?: string;
  scriptVersion?: ScriptVersion;
  buildBoxVersion?: BuildBoxVersion;
  nextOrderDateAttributeKey?: string;
  nextOrderDateAttributeFormat?: string;
  shopifyWebhookUrl?: any;
  verifiedEmailCustomDomain?: boolean;
  localOrderDayOfWeek?: OrderDayOfWeek;
  storeFrontAccessToken?: string;
  enableWebhook?: boolean;
  onBoardingPaymentSeen?: boolean;
  changeNextOrderDateOnBillingAttempt?: boolean;
  keepLineAttributes?: boolean;
  passwordEnabled?: boolean;
  countryCode?: string;
  countryName?: string;
  overwriteSetting?: any;
  mailchimpApiKey?: string;
  carryForwardLastOrderNote?: boolean;
  allowLocalDelivery?: boolean;
  allowLocalPickup?: boolean;
  useShopifyAssets?: boolean;
  zapietEnabled?: boolean;
  mechanicEnabled?: boolean;
  enablePauseContractsAfterMaximumOrders?: boolean;
  appstleLoyaltyApiKey?: string;
  shopifyFlowEnabled?: boolean;
  overwriteAnchorDay?: boolean;
  enableChangeBillingPlan?: boolean;
  lockBillingPlanComments?: string;
  eberLoyaltyApiKey?: string;
  eberLoyaltyPoints?: number;
  eberLoyaltyMultiplier?: number;
  eberLoyaltyEnabled?: boolean;
  upcomingEmailBufferDays?: number;
  inventoryLocations?: string;
  shipperHqApiKey?: string;
  shipperHqAuthCode?: string;
  shipperHqAccessToken?: string;
  ianaTimeZone?: string;
  shipInsureEnabled?: boolean;
}

export const defaultValue: Readonly<IShopInfo> = {
  onboardingSeen: false,
  devEnabled: false,
  loyaltyLionEnabled: false,
  growaveEnabled: false,
  yotpoEnabled: false,
  advancedCustomerPortal: false,
  transferOrderNotesToSubscription: false,
  transferOrderNoteAttributesToSubscription: false,
  transferOrderLineItemAttributesToSubscription: false,
  stopImportProcess: false,
  disableShippingPricingAutoCalculation: false,
  allowV1FormCustomerPortal: false,
  enableChangeFromNextBillingDate: false,
  enableInventoryCheck: false,
  whiteListed: false,
  enableAddJSInterceptor: false,
  reBuyEnabled: false,
  priceSyncEnabled: false,
  discountSyncEnabled: false,
  skuSyncEnabled: false,
  verifiedEmailCustomDomain: false,
  enableWebhook: false,
  onBoardingPaymentSeen: false,
  changeNextOrderDateOnBillingAttempt: false,
  keepLineAttributes: false,
  passwordEnabled: false,
  carryForwardLastOrderNote: false,
  allowLocalDelivery: false,
  allowLocalPickup: false,
  useShopifyAssets: false,
  zapietEnabled: false,
  mechanicEnabled: false,
  enablePauseContractsAfterMaximumOrders: false,
  shopifyFlowEnabled: false,
  overwriteAnchorDay: false,
  enableChangeBillingPlan: false,
  eberLoyaltyEnabled: false,
  shipInsureEnabled: false,
};
