export interface ISubscriptionWidgetSettings {
  id?: number;
  shop?: string;
  oneTimePurchaseText?: string;
  deliveryText?: string;
  purchaseOptionsText?: string;
  subscriptionOptionText?: string;
  sellingPlanSelectTitle?: string;
  tooltipTitle?: string;
  tooltipDesctiption?: any;
  subscriptionWidgetMarginTop?: string;
  subscriptionWidgetMarginBottom?: string;
  subscriptionWrapperBorderWidth?: string;
  subscriptionWrapperBorderColor?: string;
  circleBorderColor?: string;
  dotBackgroundColor?: string;
  selectPaddingTop?: string;
  selectPaddingBottom?: string;
  selectPaddingLeft?: string;
  selectPaddingRight?: string;
  selectBorderWidth?: string;
  selectBorderStyle?: string;
  selectBorderColor?: string;
  selectBorderRadius?: string;
  tooltipSubscriptionSvgFill?: string;
  tooltipColor?: string;
  tooltipBackgroundColor?: string;
  tooltipBorderTopColorBorderTopColor?: string;
  subscriptionFinalPriceColor?: string;
  subscriptionWidgetTextColor?: string;
  orderStatusManageSubscriptionTitle?: string;
  orderStatusManageSubscriptionDescription?: string;
  orderStatusManageSubscriptionButtonText?: string;
  showTooltipOnClick?: boolean;
  subscriptionOptionSelectedByDefault?: boolean;
  widgetEnabled?: boolean;
  showTooltip?: boolean;
  sellingPlanTitleText?: string;
  oneTimePriceText?: string;
  selectedPayAsYouGoSellingPlanPriceText?: string;
  selectedPrepaidSellingPlanPriceText?: string;
  selectedDiscountFormat?: string;
  manageSubscriptionBtnFormat?: string;
  tooltipDescriptionOnPrepaidPlan?: any;
  tooltipDescriptionOnMultipleDiscount?: any;
  tooltipDescriptionCustomization?: any;
  showStaticTooltip?: boolean;
  showAppstleLink?: boolean;
  subscriptionPriceDisplayText?: any;
  sortByDefaultSequence?: boolean;
  showSubOptionBeforeOneTime?: boolean;
  showCheckoutSubscriptionBtn?: boolean;
  totalPricePerDeliveryText?: string;
  widgetEnabledOnSoldVariant?: boolean;
  enableCartWidgetFeature?: boolean;
  switchRadioButtonWidget?: boolean;
  formMappingAttributeName?: string;
  formMappingAttributeSelector?: string;
  quickViewModalPollingSelector?: string;
  updatePriceOnQuantityChange?: string;
  widgetParentSelector?: string;
  quantitySelector?: string;
  loyaltyDetailsLabelText?: string;
  loyaltyPerkDescriptionText?: any;
  detectVariantFromURLParams?: boolean;
  disableQueryParamsUpdate?: boolean;
}

export const defaultValue: Readonly<ISubscriptionWidgetSettings> = {
  showTooltipOnClick: false,
  subscriptionOptionSelectedByDefault: false,
  widgetEnabled: false,
  showTooltip: false,
  showStaticTooltip: false,
  showAppstleLink: false,
  sortByDefaultSequence: false,
  showSubOptionBeforeOneTime: false,
  showCheckoutSubscriptionBtn: false,
  widgetEnabledOnSoldVariant: false,
  enableCartWidgetFeature: false,
  switchRadioButtonWidget: false,
  detectVariantFromURLParams: false,
  disableQueryParamsUpdate: false
};
