package com.et.domain.enumeration;

/**
 * The BulkAutomationType enumeration.
 */
public enum BulkAutomationType {
    EXPORT,
    EXPORT_ACTIVITY_LOGS,
    MIGRATION,
    UPDATE_BILLING_INTERVAL,
    UPDATE_DELIVERY_PRICE,
    UPDATE_STATUS,
    UPDATE_DELIVERY_METHOD,
    HIDE_SUBSCRIPTIONS,
    UPDATE_NEXT_BILLING_DATE_TIME,
    UPDATE_NEXT_BILLING_DATE,
    REPLACE_REMOVED_VARIANT,
    UPDATE_LINE_PRICE,
    REPLACE_PRODUCT,
    DELETE_REMOVED_PRODUCT,
    UPDATE_MIN_MAX_CYCLES,
    ADD_REMOVE_DISCOUNT_CODE,
    UPDATE_DELIVERY_METHOD_TYPE,
    ADD_PRODUCT
}
