package com.et.domain.enumeration;

/**
 * The EmailSettingType enumeration.
 */
public enum EmailSettingType {
    SUBSCRIPTION_CREATED, TRANSACTION_FAILED, UPCOMING_ORDER, EXPIRING_CREDIT_CARD, SHIPPING_ADDRESS_UPDATED, ORDER_FREQUENCY_UPDATED, NEXT_ORDER_DATE_UPDATED, SUBSCRIPTION_PAUSED, SUBSCRIPTION_CANCELLED, SUBSCRIPTION_RESUMED, SUBSCRIPTION_PRODUCT_ADDED, SUBSCRIPTION_PRODUCT_REMOVED, SUBSCRIPTION_PRODUCT_REPLACED, SECURITY_CHALLENGE, SUBSCRIPTION_MANAGEMENT_LINK, ORDER_SKIPPED, BULK_ALL_SUBSCRIBERS,BULK_ACTIVE_SUBSCRIBERS_ONLY,BULK_PAUSED_SUBSCRIBERS_ONLY,BULK_CANCELLED_SUBSCRIBERS_ONLY,OUT_OF_STOCK,TRANSACTION_SUCCESS
}
