package com.et.domain.enumeration;

/**
 * The RetryAttempts enumeration.
 */
public enum RetryAttempts {
    ONE_ATTEMPT, TWO_ATTEMPTS, THREE_ATTEMPTS, FOUR_ATTEMPTS, FIVE_ATTEMPTS, SIX_ATTEMPTS, SEVEN_ATTEMPTS, EIGHT_ATTEMPTS, NINE_ATTEMPTS, TEN_ATTEMPTS, ELEVEN_ATTEMPTS, TWELVE_ATTEMPTS, THIRTEEN_ATTEMPTS, FOURTEEN_ATTEMPTS, FIFTEEN_ATTEMPTS
}
